export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES"
export const ADD_NEW_ARTICLE = "ADD_NEW_ARTICLE"
export const ADD_NEW_USER_INFORMATION = "ADD_NEW_USER_INFORMATION"
export const USER_ENTRANCE = "USER_ENTRANCE"
export const USER_ENTRANCE_FALSE = "USER_ENTRANCE_FALSE"
export const USER_EXIT = "USER_EXIT"
export const GET_ALL_AUTHOR_ARTICLES = "GET_ALL_AUTHOR_ARTICLES"
export const DELETE_ARTICLE = "DELETE_ARTICLE"
export const USER_DELETE = "USER_DELETE"
export const NEW_COMMENT = "NEW_COMMENT"
export const CHANGE_PAGE = "CHANGE_PAGE"
export const AUTHOR_FLAG_FALSE = "AUTHOR_FLAG_FALSE"
export const AUTHOR_FLAG_TRUE = "AUTHOR_FLAG_TRUE"
export const CHANGE_PAGE_AUTHOR = "CHANGE_PAGE_AUTHOR"



